SELECT 
    id,
    result,
    price,
    "propertyDetailsUrl" as propertydetailsurl,
    "propertyType" as propertytype,
    UPPER(state) as state,
    postcode,
    "unitNumber" as unitnumber,
    "streetNumber" as streetnumber,
    "streetName" as streetname,
    "streetType" as streettype,
    suburb,
    bathrooms,
    bedrooms,
    carspaces,
    "geoLocation.latitude" as lat,
    "geoLocation.longitude" as long,
    "agencyId" as agencyid,
    "agencyName" as agencyname,
    "agencyProfilePageUrl" as agencydetailsurl,
    agent,
    url, 
    TO_TIMESTAMP("execution_time", 'YYYY-MM-DDTHH24:MI:ssZ') as execution_time
FROM {{ source('domain_dwh', 'raw_sales_listings') }}