extract: 
  log_path: ""
  target_cities:
    - Sydney
    - Melbourne
    - Adelaide
  api_urls:
    sales_results: https://api.domain.com.au/v1/salesResults/{city}
    sales_listings: https://api.domain.com.au/v1/salesResults/{city}/listings
load:
  method: "cloud_storage"
  mode: "azure"
  file_format: "parquet"
  chunksize: 1000
  key_columns:
    sales_results:
      - city
      - lastModifiedDateTime
    sales_listings:
      - id
      - propertyDetailsUrl
      - result
meta: 
  log_table: "pipeline_logs"